name: "trocr"
platform: "tensorrt_plan"
max_batch_size: 16
input [
  {
    name: "pixel_values"
    data_type: TYPE_FP16
    dims: [ 3, 384, 384 ]
  }
]
output [
  {
    name: "last_hidden_state"
    data_type: TYPE_FP16
    dims: [ 576, 768 ]
  }
]
dynamic_batching {
  preferred_batch_size: [ 4, 8, 16 ]
  max_queue_delay_microseconds: 50000
}
instance_group [
  {
    count: 2
    kind: KIND_GPU
  }
]
